language: go

go:
  - 1.5

before_install:
- go get github.com/golang/lint/golint
- go get github.com/GeertJohan/fgt

script:
- fgt golint $(find ./ | grep .go$ | grep -v card.pb.go)
- go test -v ./...