// Code generated by protoc-gen-go.
// source: card.proto
// DO NOT EDIT!

/*
Package card is a generated protocol buffer package.

It is generated from these files:
	card.proto

It has these top-level messages:
	Card
*/
package card

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

// The action to take along with the card
type Card_Action int32

const (
	Card_NONE Card_Action = 0
)

var Card_Action_name = map[int32]string{
	0: "NONE",
}
var Card_Action_value = map[string]int32{
	"NONE": 0,
}

func (x Card_Action) Enum() *Card_Action {
	p := new(Card_Action)
	*p = x
	return p
}
func (x Card_Action) String() string {
	return proto.EnumName(Card_Action_name, int32(x))
}
func (x *Card_Action) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Card_Action_value, data, "Card_Action")
	if err != nil {
		return err
	}
	*x = Card_Action(value)
	return nil
}
func (Card_Action) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Card struct {
	// A web link to the image to display
	Image *string `protobuf:"bytes,1,opt,name=image" json:"image,omitempty"`
	// The text to display with the card
	Text             *string      `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
	Action           *Card_Action `protobuf:"varint,3,opt,name=action,enum=Card_Action" json:"action,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *Card) Reset()                    { *m = Card{} }
func (m *Card) String() string            { return proto.CompactTextString(m) }
func (*Card) ProtoMessage()               {}
func (*Card) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Card) GetImage() string {
	if m != nil && m.Image != nil {
		return *m.Image
	}
	return ""
}

func (m *Card) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

func (m *Card) GetAction() Card_Action {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return Card_NONE
}

func init() {
	proto.RegisterType((*Card)(nil), "Card")
	proto.RegisterEnum("Card_Action", Card_Action_name, Card_Action_value)
}

var fileDescriptor0 = []byte{
	// 108 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x4e, 0x2c, 0x4a,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x0a, 0xe5, 0x62, 0x71, 0x06, 0xf2, 0x84, 0x78, 0xb9,
	0x58, 0x33, 0x73, 0x13, 0xd3, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x85, 0x78, 0xb8, 0x58,
	0x4a, 0x52, 0x2b, 0x4a, 0x24, 0x98, 0xc0, 0x3c, 0x19, 0x2e, 0xb6, 0xc4, 0xe4, 0x92, 0xcc, 0xfc,
	0x3c, 0x09, 0x66, 0x20, 0x9f, 0xcf, 0x88, 0x47, 0x0f, 0xa4, 0x47, 0xcf, 0x11, 0x2c, 0xa6, 0x24,
	0xc4, 0xc5, 0x06, 0x61, 0x09, 0x71, 0x70, 0xb1, 0xf8, 0xf9, 0xfb, 0xb9, 0x0a, 0x30, 0x00, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x6f, 0x51, 0x89, 0xbd, 0x63, 0x00, 0x00, 0x00,
}
