// Code generated by protoc-gen-go.
// source: card.proto
// DO NOT EDIT!

/*
Package card is a generated protocol buffer package.

It is generated from these files:
	card.proto

It has these top-level messages:
	Empty
	Card
	CardList
*/
package card

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

// The action to take along with the card
type Card_Action int32

const (
	Card_NONE     Card_Action = 0
	Card_VISITURL Card_Action = 1
)

var Card_Action_name = map[int32]string{
	0: "NONE",
	1: "VISITURL",
}
var Card_Action_value = map[string]int32{
	"NONE":     0,
	"VISITURL": 1,
}

func (x Card_Action) String() string {
	return proto.EnumName(Card_Action_name, int32(x))
}
func (Card_Action) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Card struct {
	// A web link to the image to display
	Image string `protobuf:"bytes,1,opt,name=image" json:"image,omitempty"`
	// The text to display with the card
	Text   string      `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
	Action Card_Action `protobuf:"varint,3,opt,name=action,enum=card.Card_Action" json:"action,omitempty"`
	// The date the card was created
	CreatedDate int64 `protobuf:"varint,4,opt,name=created_date,json=createdDate" json:"created_date,omitempty"`
	// The date from which the card should be applied
	ApplicationDate int64 `protobuf:"varint,5,opt,name=application_date,json=applicationDate" json:"application_date,omitempty"`
	// The date from which the card can be removed
	ExpirationDate int64 `protobuf:"varint,6,opt,name=expiration_date,json=expirationDate" json:"expiration_date,omitempty"`
	// The chosen priority of the card
	Priority int32 `protobuf:"varint,7,opt,name=priority" json:"priority,omitempty"`
	// A hash id of the card
	Hash string `protobuf:"bytes,8,opt,name=hash" json:"hash,omitempty"`
}

func (m *Card) Reset()                    { *m = Card{} }
func (m *Card) String() string            { return proto.CompactTextString(m) }
func (*Card) ProtoMessage()               {}
func (*Card) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type CardList struct {
	Cards []*Card `protobuf:"bytes,1,rep,name=cards" json:"cards,omitempty"`
}

func (m *CardList) Reset()                    { *m = CardList{} }
func (m *CardList) String() string            { return proto.CompactTextString(m) }
func (*CardList) ProtoMessage()               {}
func (*CardList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CardList) GetCards() []*Card {
	if m != nil {
		return m.Cards
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "card.Empty")
	proto.RegisterType((*Card)(nil), "card.Card")
	proto.RegisterType((*CardList)(nil), "card.CardList")
	proto.RegisterEnum("card.Card_Action", Card_Action_name, Card_Action_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion2

// Client API for CardService service

type CardServiceClient interface {
	// Gets the cards currently held in the system
	GetCards(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CardList, error)
	// Adds the cards in the list to the system - returns the resulting card list
	AddCards(ctx context.Context, in *CardList, opts ...grpc.CallOption) (*CardList, error)
}

type cardServiceClient struct {
	cc *grpc.ClientConn
}

func NewCardServiceClient(cc *grpc.ClientConn) CardServiceClient {
	return &cardServiceClient{cc}
}

func (c *cardServiceClient) GetCards(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CardList, error) {
	out := new(CardList)
	err := grpc.Invoke(ctx, "/card.CardService/GetCards", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardServiceClient) AddCards(ctx context.Context, in *CardList, opts ...grpc.CallOption) (*CardList, error) {
	out := new(CardList)
	err := grpc.Invoke(ctx, "/card.CardService/AddCards", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CardService service

type CardServiceServer interface {
	// Gets the cards currently held in the system
	GetCards(context.Context, *Empty) (*CardList, error)
	// Adds the cards in the list to the system - returns the resulting card list
	AddCards(context.Context, *CardList) (*CardList, error)
}

func RegisterCardServiceServer(s *grpc.Server, srv CardServiceServer) {
	s.RegisterService(&_CardService_serviceDesc, srv)
}

func _CardService_GetCards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServiceServer).GetCards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/card.CardService/GetCards",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServiceServer).GetCards(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardService_AddCards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CardList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServiceServer).AddCards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/card.CardService/AddCards",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServiceServer).AddCards(ctx, req.(*CardList))
	}
	return interceptor(ctx, in, info, handler)
}

var _CardService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "card.CardService",
	HandlerType: (*CardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCards",
			Handler:    _CardService_GetCards_Handler,
		},
		{
			MethodName: "AddCards",
			Handler:    _CardService_AddCards_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0x91, 0x5d, 0x4b, 0xfb, 0x30,
	0x14, 0xc6, 0xf7, 0xd2, 0x76, 0xf9, 0x9f, 0x8e, 0xae, 0xff, 0xe0, 0x45, 0xd8, 0x55, 0xed, 0x8d,
	0x13, 0xa4, 0x17, 0xf5, 0x13, 0x0c, 0x1d, 0x32, 0x18, 0x13, 0x32, 0xf5, 0x56, 0x62, 0x1b, 0x5d,
	0xc0, 0xd9, 0x90, 0x06, 0xd9, 0xbe, 0x8f, 0x1f, 0xd4, 0xbc, 0x0c, 0x3b, 0xf4, 0x26, 0x9c, 0xf3,
	0x9c, 0xdf, 0x79, 0xda, 0x27, 0x01, 0xa8, 0x98, 0xaa, 0x0b, 0xa9, 0x1a, 0xdd, 0xe0, 0xc0, 0xd6,
	0xf9, 0x08, 0xc2, 0xc5, 0x4e, 0xea, 0x43, 0xfe, 0x35, 0x80, 0xe0, 0xc6, 0x28, 0xf8, 0x0c, 0x42,
	0xb1, 0x63, 0x6f, 0x9c, 0xf4, 0xb3, 0xfe, 0xec, 0x1f, 0xf5, 0x0d, 0xc6, 0x10, 0x68, 0xbe, 0xd7,
	0x64, 0xe0, 0x44, 0x57, 0xe3, 0x4b, 0x88, 0x58, 0xa5, 0x45, 0xf3, 0x41, 0x86, 0x46, 0x4d, 0xca,
	0xff, 0x85, 0xb3, 0xb7, 0x2e, 0xc5, 0xdc, 0x0d, 0xe8, 0x11, 0xc0, 0xe7, 0x30, 0xae, 0x14, 0x67,
	0x9a, 0xd7, 0xcf, 0xb5, 0x39, 0x49, 0x60, 0x16, 0x86, 0x34, 0x3e, 0x6a, 0xb7, 0xe6, 0x30, 0x6e,
	0x29, 0x93, 0xf2, 0x5d, 0x54, 0xcc, 0x6e, 0x78, 0x2c, 0x74, 0xd8, 0xe4, 0x44, 0x77, 0xe8, 0x05,
	0x4c, 0xf8, 0x5e, 0x0a, 0x75, 0x42, 0x46, 0x8e, 0x4c, 0x3a, 0xd9, 0x81, 0x53, 0x40, 0x52, 0x89,
	0x46, 0x09, 0x7d, 0x20, 0x23, 0x43, 0x84, 0xf4, 0xa7, 0xb7, 0x89, 0xb6, 0xac, 0xdd, 0x12, 0xe4,
	0x13, 0xd9, 0x3a, 0xcf, 0x20, 0xf2, 0x3f, 0x8e, 0x11, 0x04, 0xeb, 0xfb, 0xf5, 0x22, 0xed, 0xe1,
	0x31, 0xa0, 0xa7, 0xe5, 0x66, 0xf9, 0xf0, 0x48, 0x57, 0x69, 0x3f, 0xbf, 0x02, 0x64, 0xf3, 0xad,
	0x44, 0xab, 0x71, 0x06, 0xa1, 0x0d, 0xdc, 0x9a, 0x9b, 0x1a, 0xce, 0xe2, 0x12, 0xba, 0xf8, 0xd4,
	0x0f, 0xca, 0x57, 0x88, 0x6d, 0xbb, 0xe1, 0xea, 0x53, 0x54, 0x36, 0x22, 0xba, 0xe3, 0xda, 0x2a,
	0x2d, 0x8e, 0x3d, 0xed, 0x2e, 0x7f, 0x9a, 0x74, 0xab, 0xd6, 0x39, 0xef, 0x61, 0xf3, 0x9d, 0x79,
	0x5d, 0x7b, 0xf4, 0xd7, 0xf4, 0x2f, 0xfd, 0x12, 0xb9, 0x27, 0xbd, 0xfe, 0x0e, 0x00, 0x00, 0xff,
	0xff, 0x23, 0xbc, 0x46, 0x7f, 0xe0, 0x01, 0x00, 0x00,
}
