// Code generated by protoc-gen-go.
// source: card.proto
// DO NOT EDIT!

/*
Package card is a generated protocol buffer package.

It is generated from these files:
	card.proto

It has these top-level messages:
	Empty
	Card
	DeleteRequest
	CardList
*/
package card

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The action to take along with the card
type Card_Action int32

const (
	Card_NONE     Card_Action = 0
	Card_VISITURL Card_Action = 1
	Card_RATING   Card_Action = 2
	Card_RATE     Card_Action = 3
)

var Card_Action_name = map[int32]string{
	0: "NONE",
	1: "VISITURL",
	2: "RATING",
	3: "RATE",
}
var Card_Action_value = map[string]int32{
	"NONE":     0,
	"VISITURL": 1,
	"RATING":   2,
	"RATE":     3,
}

func (x Card_Action) String() string {
	return proto.EnumName(Card_Action_name, int32(x))
}
func (Card_Action) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type Card_Channel int32

const (
	Card_MUSIC  Card_Channel = 0
	Card_ISSUES Card_Channel = 1
)

var Card_Channel_name = map[int32]string{
	0: "MUSIC",
	1: "ISSUES",
}
var Card_Channel_value = map[string]int32{
	"MUSIC":  0,
	"ISSUES": 1,
}

func (x Card_Channel) String() string {
	return proto.EnumName(Card_Channel_name, int32(x))
}
func (Card_Channel) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 1} }

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Card struct {
	// A web link to the image to display
	Image string `protobuf:"bytes,1,opt,name=image" json:"image,omitempty"`
	// The text to display with the card
	Text   string      `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
	Action Card_Action `protobuf:"varint,3,opt,name=action,enum=card.Card_Action" json:"action,omitempty"`
	// The date the card was created
	CreatedDate int64 `protobuf:"varint,4,opt,name=created_date,json=createdDate" json:"created_date,omitempty"`
	// The date from which the card should be applied
	ApplicationDate int64 `protobuf:"varint,5,opt,name=application_date,json=applicationDate" json:"application_date,omitempty"`
	// The date from which the card can be removed
	ExpirationDate int64 `protobuf:"varint,6,opt,name=expiration_date,json=expirationDate" json:"expiration_date,omitempty"`
	// The chosen priority of the card
	Priority int32 `protobuf:"varint,7,opt,name=priority" json:"priority,omitempty"`
	// A hash id of the card
	Hash string `protobuf:"bytes,8,opt,name=hash" json:"hash,omitempty"`
	// Metadata for the action
	ActionMetadata []string     `protobuf:"bytes,9,rep,name=action_metadata,json=actionMetadata" json:"action_metadata,omitempty"`
	Channel        Card_Channel `protobuf:"varint,10,opt,name=channel,enum=card.Card_Channel" json:"channel,omitempty"`
}

func (m *Card) Reset()                    { *m = Card{} }
func (m *Card) String() string            { return proto.CompactTextString(m) }
func (*Card) ProtoMessage()               {}
func (*Card) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type DeleteRequest struct {
	Hash string `protobuf:"bytes,1,opt,name=hash" json:"hash,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type CardList struct {
	Cards []*Card `protobuf:"bytes,1,rep,name=cards" json:"cards,omitempty"`
}

func (m *CardList) Reset()                    { *m = CardList{} }
func (m *CardList) String() string            { return proto.CompactTextString(m) }
func (*CardList) ProtoMessage()               {}
func (*CardList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CardList) GetCards() []*Card {
	if m != nil {
		return m.Cards
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "card.Empty")
	proto.RegisterType((*Card)(nil), "card.Card")
	proto.RegisterType((*DeleteRequest)(nil), "card.DeleteRequest")
	proto.RegisterType((*CardList)(nil), "card.CardList")
	proto.RegisterEnum("card.Card_Action", Card_Action_name, Card_Action_value)
	proto.RegisterEnum("card.Card_Channel", Card_Channel_name, Card_Channel_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for CardService service

type CardServiceClient interface {
	// Gets the cards currently held in the system
	GetCards(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CardList, error)
	// Adds the cards in the list to the system - returns the resulting card list
	AddCards(ctx context.Context, in *CardList, opts ...grpc.CallOption) (*CardList, error)
	// Deletes existing cards
	DeleteCards(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*CardList, error)
}

type cardServiceClient struct {
	cc *grpc.ClientConn
}

func NewCardServiceClient(cc *grpc.ClientConn) CardServiceClient {
	return &cardServiceClient{cc}
}

func (c *cardServiceClient) GetCards(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CardList, error) {
	out := new(CardList)
	err := grpc.Invoke(ctx, "/card.CardService/GetCards", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardServiceClient) AddCards(ctx context.Context, in *CardList, opts ...grpc.CallOption) (*CardList, error) {
	out := new(CardList)
	err := grpc.Invoke(ctx, "/card.CardService/AddCards", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardServiceClient) DeleteCards(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*CardList, error) {
	out := new(CardList)
	err := grpc.Invoke(ctx, "/card.CardService/DeleteCards", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CardService service

type CardServiceServer interface {
	// Gets the cards currently held in the system
	GetCards(context.Context, *Empty) (*CardList, error)
	// Adds the cards in the list to the system - returns the resulting card list
	AddCards(context.Context, *CardList) (*CardList, error)
	// Deletes existing cards
	DeleteCards(context.Context, *DeleteRequest) (*CardList, error)
}

func RegisterCardServiceServer(s *grpc.Server, srv CardServiceServer) {
	s.RegisterService(&_CardService_serviceDesc, srv)
}

func _CardService_GetCards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServiceServer).GetCards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/card.CardService/GetCards",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServiceServer).GetCards(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardService_AddCards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CardList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServiceServer).AddCards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/card.CardService/AddCards",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServiceServer).AddCards(ctx, req.(*CardList))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardService_DeleteCards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServiceServer).DeleteCards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/card.CardService/DeleteCards",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServiceServer).DeleteCards(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CardService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "card.CardService",
	HandlerType: (*CardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCards",
			Handler:    _CardService_GetCards_Handler,
		},
		{
			MethodName: "AddCards",
			Handler:    _CardService_AddCards_Handler,
		},
		{
			MethodName: "DeleteCards",
			Handler:    _CardService_DeleteCards_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("card.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 425 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x92, 0xcb, 0x8e, 0xd3, 0x30,
	0x14, 0x86, 0x27, 0x93, 0x6b, 0x4f, 0x86, 0x4c, 0x30, 0x2c, 0xac, 0x59, 0x85, 0xb0, 0x60, 0x90,
	0x46, 0x5d, 0x14, 0xc4, 0xbe, 0xea, 0x44, 0xa3, 0x48, 0x6d, 0x91, 0x9c, 0x96, 0x6d, 0x65, 0x12,
	0x8b, 0x5a, 0x6a, 0x9b, 0x90, 0x18, 0xd4, 0xbe, 0x0b, 0x6f, 0xc1, 0x0b, 0xe2, 0x4b, 0x68, 0xca,
	0x65, 0x13, 0x1d, 0xff, 0xe7, 0x3b, 0xbf, 0xce, 0xef, 0x18, 0xa0, 0xa4, 0x6d, 0x35, 0x6e, 0xda,
	0x5a, 0xd4, 0xc8, 0x51, 0x75, 0xea, 0x83, 0x9b, 0xed, 0x1b, 0x71, 0x4a, 0x7f, 0xda, 0xe0, 0xcc,
	0xa4, 0x82, 0x5e, 0x82, 0xcb, 0xf7, 0xf4, 0x0b, 0xc3, 0x56, 0x62, 0xdd, 0x8f, 0x88, 0x39, 0x20,
	0x04, 0x8e, 0x60, 0x47, 0x81, 0xaf, 0xb5, 0xa8, 0x6b, 0xf4, 0x16, 0x3c, 0x5a, 0x0a, 0x5e, 0x1f,
	0xb0, 0x2d, 0xd5, 0x68, 0xf2, 0x7c, 0xac, 0xed, 0x95, 0xcb, 0x78, 0xaa, 0x1b, 0xa4, 0x07, 0xd0,
	0x2b, 0xb8, 0x29, 0x5b, 0x46, 0x05, 0xab, 0x36, 0x95, 0xfc, 0x62, 0x47, 0x0e, 0xd8, 0x24, 0xec,
	0xb5, 0x47, 0xf9, 0x91, 0x6e, 0x31, 0x6d, 0x9a, 0x1d, 0x2f, 0xa9, 0x9a, 0x30, 0x98, 0xab, 0xb1,
	0xdb, 0x0b, 0x5d, 0xa3, 0x6f, 0xe0, 0x96, 0x1d, 0x1b, 0xde, 0x5e, 0x90, 0x9e, 0x26, 0xa3, 0x41,
	0xd6, 0xe0, 0x1d, 0x04, 0x4d, 0xcb, 0xeb, 0x96, 0x8b, 0x13, 0xf6, 0x25, 0xe1, 0x92, 0xf3, 0x59,
	0x25, 0xda, 0xd2, 0x6e, 0x8b, 0x03, 0x93, 0x48, 0xd5, 0xca, 0xd8, 0x2c, 0xbc, 0xd9, 0x33, 0x41,
	0xa5, 0x31, 0xc5, 0xa3, 0xc4, 0x96, 0xed, 0xc8, 0xc8, 0x8b, 0x5e, 0x45, 0x0f, 0xe0, 0x97, 0x5b,
	0x7a, 0x38, 0xb0, 0x1d, 0x06, 0x9d, 0x1d, 0x5d, 0x64, 0x9f, 0x99, 0x0e, 0xf9, 0x8d, 0xa4, 0x1f,
	0xc0, 0x33, 0xf7, 0x81, 0x02, 0x70, 0x96, 0x1f, 0x97, 0x59, 0x7c, 0x85, 0x6e, 0x20, 0xf8, 0x94,
	0x17, 0xf9, 0x6a, 0x4d, 0xe6, 0xb1, 0x85, 0x00, 0x3c, 0x32, 0x5d, 0xe5, 0xcb, 0xa7, 0xf8, 0x5a,
	0x31, 0xb2, 0xce, 0x62, 0x3b, 0x4d, 0xc0, 0xef, 0xbd, 0xd0, 0x08, 0xdc, 0xc5, 0xba, 0xc8, 0x67,
	0x72, 0x52, 0xb2, 0x79, 0x51, 0xac, 0xb3, 0x22, 0xb6, 0xd2, 0xd7, 0xf0, 0xec, 0x91, 0xed, 0x98,
	0x60, 0x84, 0x7d, 0xfd, 0xc6, 0x3a, 0x71, 0x4e, 0x65, 0x0d, 0xa9, 0xd2, 0x07, 0x08, 0xd4, 0x5e,
	0x73, 0x2e, 0xfb, 0x09, 0xb8, 0x6a, 0xd1, 0x4e, 0x02, 0xf6, 0x7d, 0x38, 0x81, 0x61, 0x6d, 0x62,
	0x1a, 0x93, 0x1f, 0x16, 0x84, 0xea, 0x5c, 0xb0, 0xf6, 0x3b, 0x2f, 0xd5, 0x7f, 0x09, 0x9e, 0x98,
	0x50, 0x4a, 0x87, 0x42, 0x83, 0xeb, 0x17, 0x73, 0x17, 0x0d, 0xb3, 0xca, 0x3a, 0xbd, 0x92, 0xb7,
	0x12, 0x4c, 0xab, 0xca, 0xa0, 0x7f, 0x75, 0xff, 0x43, 0xbf, 0x87, 0xd0, 0xec, 0x6e, 0x06, 0x5e,
	0x18, 0xe0, 0x8f, 0x38, 0xff, 0x4e, 0x7d, 0xf6, 0xf4, 0xeb, 0x7d, 0xf7, 0x2b, 0x00, 0x00, 0xff,
	0xff, 0x79, 0xf6, 0x77, 0x70, 0xcb, 0x02, 0x00, 0x00,
}
